version: '3'

services:
  proxy:
    image: ghcr.io/friddle/go-docker-proxy:master
    environment:
      - CUSTOM_DOMAIN=your-domain.com
      - MODE=production
      - PORT=5000
    restart: always
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
